DEFAULT_TIMESPAN: 1
PAGE_SIZE: 300
APP_NAME: kspyder
DUMP_JSON: true
# Challenge the dependency b/w logging handler and config.py
LOG_CONFIG: logging_verbose

Modules:
  - odooRPCConnector
  - prestashopSQLConnector
  - azureSQLConnector
  - azureRGraphConnector
  - pandaPipelinesEngine
  - pandaXLSConnector
  - pandaSQLConnector
  - mongoDBConnector
  - aliyunCLIConnector
  - aliyunRAMConnector