Steps:

  - Name: Build.StarterMetadataRequest
    Job: set_static_data
    Output: StarterRequest_Metadata
    Params:
      data:
        - dimension: topics
        - dimension: frequencies
        - dimension: granularities
        - dimension: licenses
        - dimension: attachmentTypes

  - Name: Build.StarterDatasetRequest
    Job: set_static_data
    Output: StarterRequest_Datasets
    Params:
      data:
        - start_token: 1
          batch_size: 2000

  - Name: GetToMongo.DiDoMetadata
    Job: get_data_to_mongo
    Output: DiDoMetadata
    Input: StarterRequest_Metadata.data
    Params:
      from_worker: openDataConnector
      model_name: DiDoMetadata

  # - Name: GetToMongo.DiDoDatasets
  #   Job: get_data_to_mongo
  #   Output: DiDoDatasets
  #   Input: StarterRequest_Datasets.data
  #   Params:
  #     from_worker: openDataConnector
  #     model_name: DiDoDatasetCatalogue

  # - Name: GetToMongo.MelodiCatalogue
  #   Job: get_data_to_mongo
  #   Output: MelodiDatasetCatalogue
  #   Params:
  #     from_worker: openDataConnector
  #     model_name: MelodiDatasetCatalogue

  # - Name: Extract.MelodiDatasetIds
  #   Worker: mongoDBConnector
  #   Job: aggregate_data
  #   Output: MelodiDatasetIds
  #   Params:
  #     collection_name: OpenDataFR.INSEE.MelodiDatasetCatalogue
  #     pipeline:
  #       - $project:
  #           id: $identifier
  #       - $unset:
  #           - _id
  
  # - Name: GetToMongo.MelodiCatalogEntries
  #   Job: get_data_to_mongo
  #   Input: MelodiDatasetIds.data
  #   Output: MelodiCatalogEntries
  #   Params:
  #     from_worker: openDataConnector
  #     model_name: MelodiCatalogEntries

  # - Name: GetToMongo.MelodiDatasets
  #   Job: get_data_to_mongo
  #   Input: MelodiDatasetIds.data
  #   Output: MelodiDatasets
  #   Params:
  #     from_worker: openDataConnector
  #     model_name: MelodiDatasets

  # - Name: Extract.DatafileRids
  #   Worker: mongoDBConnector
  #   Job: aggregate_data
  #   Output: DatafileRids
  #   Params:
  #     collection_name: OpenData.DiDo.Datafiles.Summary
  #     pipeline:
  #       - $project:
  #           rid: $datafile_rid
  #           millesime: 1
  #       - $unset: 
  #           - _id 

  # - Name: Get.DatafilesByRid
  #   Job: get_data_to_mongo
  #   Input: DatafileRids.data
  #   Output: OpenData.DiDo.Datafiles
  #   Params:
  #     from_worker: openDataConnector
  #     model_name: DiDoDatafiles



