DEFAULT_TIMESPAN: 1
PAGE_SIZE: 300
APP_NAME: kspyder_local

CONNECTOR_MAP:
  azureRG: 
    connector: azureResourceGraph
    client: AzureRGConnector
  odoo:
    connector: odooRPC
    client: OdooRPCConnector
  prestashop:
    connector: prestashopSQL
    client: prestashopSQLExtractor
  mongoDB: 
    connector: mongo_connector
    client: MongoDBConnector
  pandaXLS: 
    connector: PandaXLS
    client: PandaXLSConnector
  pandaSQL: 
    connector: PandaSQL
    client: PandaSQLConnector


local:
  DUMP_JSON: true
  LOG_CONFIG: logging_semiverbose
  ODOO_PROFILE: PLACEHOLDER_PROFILE
  PS_PROFILE: PLACEHOLDER_PROFILE
  SECRET_STORE: AZURE_KEY_VAULT
  AZURE_PROFILE: AZURE_SQL_PROD
  AZ_PRICING_PROFILE: Azure_Pricing
  AZURERG_DEFAULT_SCOPE: 'EAEU Europe Hub'

local_noKV:
  DUMP_JSON: true
  LOG_CONFIG: logging_semiverbose
  ODOO_PROFILE: PLACEHOLDER_PROFILE
  PS_PROFILE: PLACEHOLDER_PROFILE
  SECRET_STORE: local_only/secrets.yaml
  AZURE_PROFILE: null
  AZ_PRICING_PROFILE: null
  AZURERG_DEFAULT_SCOPE: null
