DEFAULT_TIMESPAN: 1
PAGE_SIZE: 300

CONNECTOR_MAP:
  azureRG: azureResourceGraph

local:
  DUMP_JSON: true
  LOG_CONFIG: logging_verbose
  ODOO_PROFILE: PLACEHOLDER_PROFILE
  PS_PROFILE: PLACEHOLDER_PROFILE
  AZURE_PROFILE: PLACEHOLDER_PROFILE
