version: 1

loggers:
  main:
    handlers: [console]
    level: INFO

handlers:
  console:
    class: logging.StreamHandler
    formatter: base
    stream: ext://sys.stdout

formatters:
  base:
    format: '%(asctime)s - %(name)s - %(levelname)s :: %(filename)s :: %(message)s'

